### ISSUE TITLE
pip install tudou 报错怎么回事？

### ISSUE THREAD

**Issue by Evan-YZP** [fennuDetudou/tudouNLP#3]
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\YuZP\AppData\Local\Temp\pip-build-0gsa406_\tudou\setup.py", line 6, in <module>
        long_description=open('README.md').read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 39: illegal multibyte sequence

这个setup文件的问题吗

**Comment by MichaelangeloHuo** [comment]
这种编码问题使用的windows吧？

**Comment by PeikaiLi** [comment]
不能再window上运行吗？
